/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Display: typeof import('./src/components/Display.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Form: typeof import('./src/components/Form.vue')['default']
    Hct: typeof import('./src/components/Hct.vue')['default']
    HctVisualization: typeof import('./src/components/HctVisualization.vue')['default']
    RenderChart: typeof import('./src/components/RenderChart.vue')['default']
    RenderUI: typeof import('./src/components/RenderUI.vue')['default']
    ThemeController: typeof import('./src/components/ThemeController.vue')['default']
    ThemeProvider: typeof import('./src/components/ThemeProvider.vue')['default']
  }
}
